# We're creating a new type named `Quote` to represent a quote and its author.
type TODO {
  task: String!
  realm: String!
  completed: Boolean @default(value: false)
}

type Query {
  # A new field in the Query operation to retrieve all quotes.
  realmToDo: [Quote!]
}